### ISSUE TITLE
Upstream data error

### ISSUE THREAD

**Issue by jmp2626** [evjrob/bayes-bet#31]
Hey Everett, noticed that the upstream data dependency probably broke again with the all star break. 

Was wondering if it would be possible to fix or for the the new model evaluation pipeline to get pushed! Eagerly waiting!!

Hope all is well

**Comment by evjrob** [comment]
Shoot, it looks like you’re correct. I must have made some mistake when adjusting the modelling workflow to the NHL API change back in November. 

Life has been a bit busy, but I’ll do my best to get this working again as soon as possible. I apologize for the inconvenience in the meanwhile.

**Comment by jmp2626** [comment]
No worries! Thankful for all your work!

I think I have identified the issue. Without seeing the logs can try and fork and make the edits!

**Comment by evjrob** [comment]
Absolutely! If you’re comfortable with that, I’m super happy to review a PR and put it through some testing in my staging environment.

**Comment by evjrob** [comment]
Hey! The issue turned out to be quite simple. The data ingestion task that pulls the raw data from the NHL API just needs to determine the current season from the data before any filtering occurs. This issue has been resolved in my test environment with the changes included in https://github.com/evjrob/bayes-bet/pull/34. 

The model should run successfully tomorrow morning and it will back fill the predictions from the missed days. Apologize for the delay!
